### PR TITLE
TaskRecording

### PR DESCRIPTION
**Pull request by mavaylon1**
This PR creates the ASE container to house the StatesTable, ActionsTable, and EventsTable.

### CODE REVIEW

**Comment by mavaylon1** [comment]
Fix #34

**Comment by mavaylon1** [comment]
This is not ready for a review.
@oruebel Take a look and let me know if there is anything else you were thinking of. 
@rly I will dig a little deeper with breakpoint but when I do a roundtrip test it says that events, actions, and states don't have a parent. I checked the instance of ASE in my test and it does not have children. From my understanding the __fields__ with the child key should've done that. I just wanted this out there as I dig around.

**Comment by mavaylon1** [comment]
@oruebel I did a pass through the tests, the new code, and the schema. There is no changelog and we don't have a tutorial besides a user day demo.

**Comment by oruebel** [comment]
> There is no changelog

I would start adding changelog information here https://github.com/rly/ndx-beadl/blob/main/docs/source/release_notes.rst

**Comment by oruebel** [comment]
Can you please update the notebook to use the new TaskRecording module

https://github.com/rly/ndx-beadl/blob/main/docs/tutorial_nwb_userdays_2022/beadl_example_nwb_userdays_2022.ipynb

If you want, we can also rename the tutorial `tutorial_nwb_userdays_2022` folder to just `notebooks` or `tutorial`

**Comment by mavaylon1** [comment]
@oruebel I made sure to update the notebook with the image from the paper. I also went through and renamed "ndx-beadl" to "ndx-Structured_Behavior" in the tutorial. I also took note of from the other PR (duration column) to where the create_extension_spec has been updated so that it is not a manual update on the schema itself. The first "log" is in the release_notes now.

**Pull request merged**
